Release 9.0

diff --git a/extra/make_debian_package b/extra/make_debian_package
--- a/extra/make_debian_package
+++ b/extra/make_debian_package
@@ -5,6 +5,14 @@ if [ ! -f /etc/debian_version ]; then
 	exit
 fi
 
+# Check for CMake
+#
+cmake --version 2> /dev/null
+if [ $? != 0 ]; then
+	echo "CMake is not installed but required for building Hiawatha."
+	exit
+fi
+
 # Checking for packages required for building a Debian package
 #
 echo "-- Checking for required packages"
diff --git a/extra/make_source_package b/extra/make_source_package
--- a/extra/make_source_package
+++ b/extra/make_source_package
@@ -9,6 +9,14 @@ fi
 mkdir build_source_package
 cd build_source_package
 
+# Check for CMake
+#
+cmake --version 2> /dev/null
+if [ $? != 0 ]; then
+	echo "CMake is not installed but required for building Hiawatha."
+	exit
+fi
+
 # Make source package
 #
 cmake ..
diff --git a/extra/make_windows_package b/extra/make_windows_package
--- a/extra/make_windows_package
+++ b/extra/make_windows_package
@@ -5,6 +5,14 @@ if [ `uname -o` != "Cygwin" ]; then
 	exit
 fi
 
+# Check for CMake
+#
+cmake --version 2> /dev/null
+if [ $? != 0 ]; then
+	echo "CMake is not installed but required for building Hiawatha."
+	exit
+fi
+
 # Checking for tools required for building a Windows package
 #
 echo "-- Checking for required tools"
